In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from pandas import Series

%matplotlib inline

In [2]:
path = 'C:/Users/Pippo/Desktop/python_examples/Projecto_Final/life_expectancy/'

df = pd.read_csv(path + 'UNdata_Life_Expectancy_males.csv')
df1 = pd.read_csv(path + 'UNdata_Life_Expectancy_females.csv')

In [3]:
# Series is a one dimension array

se = Series([1,3,5,7,9])
se

0    1
1    3
2    5
3    7
4    9
dtype: int64

In [4]:
se[2]

5

In [5]:
se2 = Series([100, 200, 300], index = ['a', 'b', 'c'])
se2

a    100
b    200
c    300
dtype: int64

In [6]:
se2['b']

200

In [7]:
salary = {'John': 3000, 'Tim': 4500, 'Rob': 5600}
salary

{'John': 3000, 'Tim': 4500, 'Rob': 5600}

In [8]:
se3 = Series(salary)
se3

John    3000
Tim     4500
Rob     5600
dtype: int64

In [9]:
se3['Tim']

4500

DataFrame

In [10]:
from pandas import DataFrame

In [11]:
df

     Country or Area    Year(s) Variant  Value
0        Afghanistan  2095-2100  Medium  75.33
1        Afghanistan  2090-2095  Medium  74.59
2        Afghanistan  2085-2090  Medium  73.89
3        Afghanistan  2080-2085  Medium  73.23
4        Afghanistan  2075-2080  Medium  72.57
5        Afghanistan  2070-2075  Medium  71.97
6        Afghanistan  2065-2070  Medium  71.36
7        Afghanistan  2060-2065  Medium  70.77
8        Afghanistan  2055-2060  Medium  70.19
9        Afghanistan  2050-2055  Medium  69.59
10       Afghanistan  2045-2050  Medium  68.97
11       Afghanistan  2040-2045  Medium  68.30
12       Afghanistan  2035-2040  Medium  67.55
13       Afghanistan  2030-2035  Medium  66.67
14       Afghanistan  2025-2030  Medium  65.67
15       Afghanistan  2020-2025  Medium  64.43
16       Afghanistan  2015-2020  Medium  62.93
17       Afghanistan  2010-2015  Medium  61.05
18       Afghanistan  2005-2010  Medium  58.87
19       Afghanistan  2000-2005  Medium  55.77
20       Afghanistan  1995-2000  Medium  53.08
21       Afghanistan  1990-1995  Medium  50.73
22       Afghanistan  1985-1990  Medium  46.80
23       Afghanistan  1980-1985  Medium  42.77
24       Afghanistan  1975-1980  Medium  39.63
25       Afghanistan  1970-1975  Medium  37.09
26       Afghanistan  1965-1970  Medium  34.86
27       Afghanistan  1960-1965  Medium  32.68
28       Afghanistan  1955-1960  Medium  30.43
29       Afghanistan  1950-1955  Medium  27.93
...              ...        ...     ...    ...
8160        Zimbabwe  2095-2100  Medium  77.51
8161        Zimbabwe  2090-2095  Medium  76.87
8162        Zimbabwe  2085-2090  Medium  76.22
8163        Zimbabwe  2080-2085  Medium  75.55
8164        Zimbabwe  2075-2080  Medium  74.86
8165        Zimbabwe  2070-2075  Medium  74.11
8166        Zimbabwe  2065-2070  Medium  73.21
8167        Zimbabwe  2060-2065  Medium  72.23
8168        Zimbabwe  2055-2060  Medium  71.19
8169        Zimbabwe  2050-2055  Medium  70.10
8170        Zimbabwe  2045-2050  Medium  68.82
8171        Zimbabwe  2040-2045  Medium  67.43
8172        Zimbabwe  2035-2040  Medium  66.03
8173        Zimbabwe  2030-2035  Medium  64.45
8174        Zimbabwe  2025-2030  Medium  62.69
8175        Zimbabwe  2020-2025  Medium  60.93
8176        Zimbabwe  2015-2020  Medium  59.91
8177        Zimbabwe  2010-2015  Medium  56.10
8178        Zimbabwe  2005-2010  Medium  47.20
8179        Zimbabwe  2000-2005  Medium  42.70
8180        Zimbabwe  1995-2000  Medium  45.06
8181        Zimbabwe  1990-1995  Medium  51.67
8182        Zimbabwe  1985-1990  Medium  57.48
8183        Zimbabwe  1980-1985  Medium  58.59
8184        Zimbabwe  1975-1980  Medium  56.10
8185        Zimbabwe  1970-1975  Medium  54.09
8186        Zimbabwe  1965-1970  Medium  52.50
8187        Zimbabwe  1960-1965  Medium  50.90
8188        Zimbabwe  1955-1960  Medium  49.00
8189        Zimbabwe  1950-1955  Medium  47.00

[8190 rows x 4 columns]

In [12]:
df = DataFrame(df, columns=['Country or Area', 'Year(s)', 'Value', 'Gender', 'Variant'])
df

     Country or Area    Year(s)  Value  Gender Variant
0        Afghanistan  2095-2100  75.33     NaN  Medium
1        Afghanistan  2090-2095  74.59     NaN  Medium
2        Afghanistan  2085-2090  73.89     NaN  Medium
3        Afghanistan  2080-2085  73.23     NaN  Medium
4        Afghanistan  2075-2080  72.57     NaN  Medium
5        Afghanistan  2070-2075  71.97     NaN  Medium
6        Afghanistan  2065-2070  71.36     NaN  Medium
7        Afghanistan  2060-2065  70.77     NaN  Medium
8        Afghanistan  2055-2060  70.19     NaN  Medium
9        Afghanistan  2050-2055  69.59     NaN  Medium
10       Afghanistan  2045-2050  68.97     NaN  Medium
11       Afghanistan  2040-2045  68.30     NaN  Medium
12       Afghanistan  2035-2040  67.55     NaN  Medium
13       Afghanistan  2030-2035  66.67     NaN  Medium
14       Afghanistan  2025-2030  65.67     NaN  Medium
15       Afghanistan  2020-2025  64.43     NaN  Medium
16       Afghanistan  2015-2020  62.93     NaN  Medium
17       Afghanistan  2010-2015  61.05     NaN  Medium
18       Afghanistan  2005-2010  58.87     NaN  Medium
19       Afghanistan  2000-2005  55.77     NaN  Medium
20       Afghanistan  1995-2000  53.08     NaN  Medium
21       Afghanistan  1990-1995  50.73     NaN  Medium
22       Afghanistan  1985-1990  46.80     NaN  Medium
23       Afghanistan  1980-1985  42.77     NaN  Medium
24       Afghanistan  1975-1980  39.63     NaN  Medium
25       Afghanistan  1970-1975  37.09     NaN  Medium
26       Afghanistan  1965-1970  34.86     NaN  Medium
27       Afghanistan  1960-1965  32.68     NaN  Medium
28       Afghanistan  1955-1960  30.43     NaN  Medium
29       Afghanistan  1950-1955  27.93     NaN  Medium
...              ...        ...    ...     ...     ...
8160        Zimbabwe  2095-2100  77.51     NaN  Medium
8161        Zimbabwe  2090-2095  76.87     NaN  Medium
8162        Zimbabwe  2085-2090  76.22     NaN  Medium
8163        Zimbabwe  2080-2085  75.55     NaN  Medium
8164        Zimbabwe  2075-2080  74.86     NaN  Medium
8165        Zimbabwe  2070-2075  74.11     NaN  Medium
8166        Zimbabwe  2065-2070  73.21     NaN  Medium
8167        Zimbabwe  2060-2065  72.23     NaN  Medium
8168        Zimbabwe  2055-2060  71.19     NaN  Medium
8169        Zimbabwe  2050-2055  70.10     NaN  Medium
8170        Zimbabwe  2045-2050  68.82     NaN  Medium
8171        Zimbabwe  2040-2045  67.43     NaN  Medium
8172        Zimbabwe  2035-2040  66.03     NaN  Medium
8173        Zimbabwe  2030-2035  64.45     NaN  Medium
8174        Zimbabwe  2025-2030  62.69     NaN  Medium
8175        Zimbabwe  2020-2025  60.93     NaN  Medium
8176        Zimbabwe  2015-2020  59.91     NaN  Medium
8177        Zimbabwe  2010-2015  56.10     NaN  Medium
8178        Zimbabwe  2005-2010  47.20     NaN  Medium
8179        Zimbabwe  2000-2005  42.70     NaN  Medium
8180        Zimbabwe  1995-2000  45.06     NaN  Medium
8181        Zimbabwe  1990-1995  51.67     NaN  Medium
8182        Zimbabwe  1985-1990  57.48     NaN  Medium
8183        Zimbabwe  1980-1985  58.59     NaN  Medium
8184        Zimbabwe  1975-1980  56.10     NaN  Medium
8185        Zimbabwe  1970-1975  54.09     NaN  Medium
8186        Zimbabwe  1965-1970  52.50     NaN  Medium
8187        Zimbabwe  1960-1965  50.90     NaN  Medium
8188        Zimbabwe  1955-1960  49.00     NaN  Medium
8189        Zimbabwe  1950-1955  47.00     NaN  Medium

[8190 rows x 5 columns]

In [13]:
df['Gender'] = 'Male'
df

     Country or Area    Year(s)  Value Gender Variant
0        Afghanistan  2095-2100  75.33   Male  Medium
1        Afghanistan  2090-2095  74.59   Male  Medium
2        Afghanistan  2085-2090  73.89   Male  Medium
3        Afghanistan  2080-2085  73.23   Male  Medium
4        Afghanistan  2075-2080  72.57   Male  Medium
5        Afghanistan  2070-2075  71.97   Male  Medium
6        Afghanistan  2065-2070  71.36   Male  Medium
7        Afghanistan  2060-2065  70.77   Male  Medium
8        Afghanistan  2055-2060  70.19   Male  Medium
9        Afghanistan  2050-2055  69.59   Male  Medium
10       Afghanistan  2045-2050  68.97   Male  Medium
11       Afghanistan  2040-2045  68.30   Male  Medium
12       Afghanistan  2035-2040  67.55   Male  Medium
13       Afghanistan  2030-2035  66.67   Male  Medium
14       Afghanistan  2025-2030  65.67   Male  Medium
15       Afghanistan  2020-2025  64.43   Male  Medium
16       Afghanistan  2015-2020  62.93   Male  Medium
17       Afghanistan  2010-2015  61.05   Male  Medium
18       Afghanistan  2005-2010  58.87   Male  Medium
19       Afghanistan  2000-2005  55.77   Male  Medium
20       Afghanistan  1995-2000  53.08   Male  Medium
21       Afghanistan  1990-1995  50.73   Male  Medium
22       Afghanistan  1985-1990  46.80   Male  Medium
23       Afghanistan  1980-1985  42.77   Male  Medium
24       Afghanistan  1975-1980  39.63   Male  Medium
25       Afghanistan  1970-1975  37.09   Male  Medium
26       Afghanistan  1965-1970  34.86   Male  Medium
27       Afghanistan  1960-1965  32.68   Male  Medium
28       Afghanistan  1955-1960  30.43   Male  Medium
29       Afghanistan  1950-1955  27.93   Male  Medium
...              ...        ...    ...    ...     ...
8160        Zimbabwe  2095-2100  77.51   Male  Medium
8161        Zimbabwe  2090-2095  76.87   Male  Medium
8162        Zimbabwe  2085-2090  76.22   Male  Medium
8163        Zimbabwe  2080-2085  75.55   Male  Medium
8164        Zimbabwe  2075-2080  74.86   Male  Medium
8165        Zimbabwe  2070-2075  74.11   Male  Medium
8166        Zimbabwe  2065-2070  73.21   Male  Medium
8167        Zimbabwe  2060-2065  72.23   Male  Medium
8168        Zimbabwe  2055-2060  71.19   Male  Medium
8169        Zimbabwe  2050-2055  70.10   Male  Medium
8170        Zimbabwe  2045-2050  68.82   Male  Medium
8171        Zimbabwe  2040-2045  67.43   Male  Medium
8172        Zimbabwe  2035-2040  66.03   Male  Medium
8173        Zimbabwe  2030-2035  64.45   Male  Medium
8174        Zimbabwe  2025-2030  62.69   Male  Medium
8175        Zimbabwe  2020-2025  60.93   Male  Medium
8176        Zimbabwe  2015-2020  59.91   Male  Medium
8177        Zimbabwe  2010-2015  56.10   Male  Medium
8178        Zimbabwe  2005-2010  47.20   Male  Medium
8179        Zimbabwe  2000-2005  42.70   Male  Medium
8180        Zimbabwe  1995-2000  45.06   Male  Medium
8181        Zimbabwe  1990-1995  51.67   Male  Medium
8182        Zimbabwe  1985-1990  57.48   Male  Medium
8183        Zimbabwe  1980-1985  58.59   Male  Medium
8184        Zimbabwe  1975-1980  56.10   Male  Medium
8185        Zimbabwe  1970-1975  54.09   Male  Medium
8186        Zimbabwe  1965-1970  52.50   Male  Medium
8187        Zimbabwe  1960-1965  50.90   Male  Medium
8188        Zimbabwe  1955-1960  49.00   Male  Medium
8189        Zimbabwe  1950-1955  47.00   Male  Medium

[8190 rows x 5 columns]

In [14]:
new_df = df.T
new_df

,0,1,2,3,4,5,6,7,8,9,...,8180,8181,8182,8183,8184,8185,8186,8187,8188,8189
Country or Area,Afghanistan,Afghanistan,Afghanistan,Afghanistan,Afghanistan,Afghanistan,Afghanistan,Afghanistan,Afghanistan,Afghanistan,...,Zimbabwe,Zimbabwe,Zimbabwe,Zimbabwe,Zimbabwe,Zimbabwe,Zimbabwe,Zimbabwe,Zimbabwe,Zimbabwe
Year(s),2095-2100,2090-2095,2085-2090,2080-2085,2075-2080,2070-2075,2065-2070,2060-2065,2055-2060,2050-2055,...,1995-2000,1990-1995,1985-1990,1980-1985,1975-1980,1970-1975,1965-1970,1960-1965,1955-1960,1950-1955
Value,75.33,74.59,73.89,73.23,72.57,71.97,71.36,70.77,70.19,69.59,...,45.06,51.67,57.48,58.59,56.1,54.09,52.5,50.9,49,47
Gender,Male,Male,Male,Male,Male,Male,Male,Male,Male,Male,...,Male,Male,Male,Male,Male,Male,Male,Male,Male,Male
Variant,Medium,Medium,Medium,Medium,Medium,Medium,Medium,Medium,Medium,Medium,...,Medium,Medium,Medium,Medium,Medium,Medium,Medium,Medium,Medium,Medium

In [15]:
new_df = df.T
df

     Country or Area    Year(s)  Value Gender Variant
0        Afghanistan  2095-2100  75.33   Male  Medium
1        Afghanistan  2090-2095  74.59   Male  Medium
2        Afghanistan  2085-2090  73.89   Male  Medium
3        Afghanistan  2080-2085  73.23   Male  Medium
4        Afghanistan  2075-2080  72.57   Male  Medium
5        Afghanistan  2070-2075  71.97   Male  Medium
6        Afghanistan  2065-2070  71.36   Male  Medium
7        Afghanistan  2060-2065  70.77   Male  Medium
8        Afghanistan  2055-2060  70.19   Male  Medium
9        Afghanistan  2050-2055  69.59   Male  Medium
10       Afghanistan  2045-2050  68.97   Male  Medium
11       Afghanistan  2040-2045  68.30   Male  Medium
12       Afghanistan  2035-2040  67.55   Male  Medium
13       Afghanistan  2030-2035  66.67   Male  Medium
14       Afghanistan  2025-2030  65.67   Male  Medium
15       Afghanistan  2020-2025  64.43   Male  Medium
16       Afghanistan  2015-2020  62.93   Male  Medium
17       Afghanistan  2010-2015  61.05   Male  Medium
18       Afghanistan  2005-2010  58.87   Male  Medium
19       Afghanistan  2000-2005  55.77   Male  Medium
20       Afghanistan  1995-2000  53.08   Male  Medium
21       Afghanistan  1990-1995  50.73   Male  Medium
22       Afghanistan  1985-1990  46.80   Male  Medium
23       Afghanistan  1980-1985  42.77   Male  Medium
24       Afghanistan  1975-1980  39.63   Male  Medium
25       Afghanistan  1970-1975  37.09   Male  Medium
26       Afghanistan  1965-1970  34.86   Male  Medium
27       Afghanistan  1960-1965  32.68   Male  Medium
28       Afghanistan  1955-1960  30.43   Male  Medium
29       Afghanistan  1950-1955  27.93   Male  Medium
...              ...        ...    ...    ...     ...
8160        Zimbabwe  2095-2100  77.51   Male  Medium
8161        Zimbabwe  2090-2095  76.87   Male  Medium
8162        Zimbabwe  2085-2090  76.22   Male  Medium
8163        Zimbabwe  2080-2085  75.55   Male  Medium
8164        Zimbabwe  2075-2080  74.86   Male  Medium
8165        Zimbabwe  2070-2075  74.11   Male  Medium
8166        Zimbabwe  2065-2070  73.21   Male  Medium
8167        Zimbabwe  2060-2065  72.23   Male  Medium
8168        Zimbabwe  2055-2060  71.19   Male  Medium
8169        Zimbabwe  2050-2055  70.10   Male  Medium
8170        Zimbabwe  2045-2050  68.82   Male  Medium
8171        Zimbabwe  2040-2045  67.43   Male  Medium
8172        Zimbabwe  2035-2040  66.03   Male  Medium
8173        Zimbabwe  2030-2035  64.45   Male  Medium
8174        Zimbabwe  2025-2030  62.69   Male  Medium
8175        Zimbabwe  2020-2025  60.93   Male  Medium
8176        Zimbabwe  2015-2020  59.91   Male  Medium
8177        Zimbabwe  2010-2015  56.10   Male  Medium
8178        Zimbabwe  2005-2010  47.20   Male  Medium
8179        Zimbabwe  2000-2005  42.70   Male  Medium
8180        Zimbabwe  1995-2000  45.06   Male  Medium
8181        Zimbabwe  1990-1995  51.67   Male  Medium
8182        Zimbabwe  1985-1990  57.48   Male  Medium
8183        Zimbabwe  1980-1985  58.59   Male  Medium
8184        Zimbabwe  1975-1980  56.10   Male  Medium
8185        Zimbabwe  1970-1975  54.09   Male  Medium
8186        Zimbabwe  1965-1970  52.50   Male  Medium
8187        Zimbabwe  1960-1965  50.90   Male  Medium
8188        Zimbabwe  1955-1960  49.00   Male  Medium
8189        Zimbabwe  1950-1955  47.00   Male  Medium

[8190 rows x 5 columns]

In [16]:
df = df.drop('Variant', axis=1)
df

     Country or Area    Year(s)  Value Gender
0        Afghanistan  2095-2100  75.33   Male
1        Afghanistan  2090-2095  74.59   Male
2        Afghanistan  2085-2090  73.89   Male
3        Afghanistan  2080-2085  73.23   Male
4        Afghanistan  2075-2080  72.57   Male
5        Afghanistan  2070-2075  71.97   Male
6        Afghanistan  2065-2070  71.36   Male
7        Afghanistan  2060-2065  70.77   Male
8        Afghanistan  2055-2060  70.19   Male
9        Afghanistan  2050-2055  69.59   Male
10       Afghanistan  2045-2050  68.97   Male
11       Afghanistan  2040-2045  68.30   Male
12       Afghanistan  2035-2040  67.55   Male
13       Afghanistan  2030-2035  66.67   Male
14       Afghanistan  2025-2030  65.67   Male
15       Afghanistan  2020-2025  64.43   Male
16       Afghanistan  2015-2020  62.93   Male
17       Afghanistan  2010-2015  61.05   Male
18       Afghanistan  2005-2010  58.87   Male
19       Afghanistan  2000-2005  55.77   Male
20       Afghanistan  1995-2000  53.08   Male
21       Afghanistan  1990-1995  50.73   Male
22       Afghanistan  1985-1990  46.80   Male
23       Afghanistan  1980-1985  42.77   Male
24       Afghanistan  1975-1980  39.63   Male
25       Afghanistan  1970-1975  37.09   Male
26       Afghanistan  1965-1970  34.86   Male
27       Afghanistan  1960-1965  32.68   Male
28       Afghanistan  1955-1960  30.43   Male
29       Afghanistan  1950-1955  27.93   Male
...              ...        ...    ...    ...
8160        Zimbabwe  2095-2100  77.51   Male
8161        Zimbabwe  2090-2095  76.87   Male
8162        Zimbabwe  2085-2090  76.22   Male
8163        Zimbabwe  2080-2085  75.55   Male
8164        Zimbabwe  2075-2080  74.86   Male
8165        Zimbabwe  2070-2075  74.11   Male
8166        Zimbabwe  2065-2070  73.21   Male
8167        Zimbabwe  2060-2065  72.23   Male
8168        Zimbabwe  2055-2060  71.19   Male
8169        Zimbabwe  2050-2055  70.10   Male
8170        Zimbabwe  2045-2050  68.82   Male
8171        Zimbabwe  2040-2045  67.43   Male
8172        Zimbabwe  2035-2040  66.03   Male
8173        Zimbabwe  2030-2035  64.45   Male
8174        Zimbabwe  2025-2030  62.69   Male
8175        Zimbabwe  2020-2025  60.93   Male
8176        Zimbabwe  2015-2020  59.91   Male
8177        Zimbabwe  2010-2015  56.10   Male
8178        Zimbabwe  2005-2010  47.20   Male
8179        Zimbabwe  2000-2005  42.70   Male
8180        Zimbabwe  1995-2000  45.06   Male
8181        Zimbabwe  1990-1995  51.67   Male
8182        Zimbabwe  1985-1990  57.48   Male
8183        Zimbabwe  1980-1985  58.59   Male
8184        Zimbabwe  1975-1980  56.10   Male
8185        Zimbabwe  1970-1975  54.09   Male
8186        Zimbabwe  1965-1970  52.50   Male
8187        Zimbabwe  1960-1965  50.90   Male
8188        Zimbabwe  1955-1960  49.00   Male
8189        Zimbabwe  1950-1955  47.00   Male

[8190 rows x 4 columns]

In [17]:
df['Value']

0       75.33
1       74.59
2       73.89
3       73.23
4       72.57
5       71.97
6       71.36
7       70.77
8       70.19
9       69.59
10      68.97
11      68.30
12      67.55
13      66.67
14      65.67
15      64.43
16      62.93
17      61.05
18      58.87
19      55.77
20      53.08
21      50.73
22      46.80
23      42.77
24      39.63
25      37.09
26      34.86
27      32.68
28      30.43
29      27.93
        ...
8160    77.51
8161    76.87
8162    76.22
8163    75.55
8164    74.86
8165    74.11
8166    73.21
8167    72.23
8168    71.19
8169    70.10
8170    68.82
8171    67.43
8172    66.03
8173    64.45
8174    62.69
8175    60.93
8176    59.91
8177    56.10
8178    47.20
8179    42.70
8180    45.06
8181    51.67
8182    57.48
8183    58.59
8184    56.10
8185    54.09
8186    52.50
8187    50.90
8188    49.00
8189    47.00
Name: Value, Length: 8190, dtype: float64

In [18]:
df.loc[2730:2759]

     Country or Area    Year(s)  Value Gender
2730         Germany  2095-2100  89.92   Male
2731         Germany  2090-2095  89.34   Male
2732         Germany  2085-2090  88.79   Male
2733         Germany  2080-2085  88.21   Male
2734         Germany  2075-2080  87.64   Male
2735         Germany  2070-2075  87.07   Male
2736         Germany  2065-2070  86.49   Male
2737         Germany  2060-2065  85.92   Male
2738         Germany  2055-2060  85.34   Male
2739         Germany  2050-2055  84.74   Male
2740         Germany  2045-2050  84.13   Male
2741         Germany  2040-2045  83.49   Male
2742         Germany  2035-2040  82.81   Male
2743         Germany  2030-2035  82.01   Male
2744         Germany  2025-2030  81.04   Male
2745         Germany  2020-2025  79.99   Male
2746         Germany  2015-2020  78.96   Male
2747         Germany  2010-2015  77.94   Male
2748         Germany  2005-2010  76.99   Male
2749         Germany  2000-2005  75.59   Male
2750         Germany  1995-2000  74.02   Male
2751         Germany  1990-1995  72.54   Male
2752         Germany  1985-1990  71.59   Male
2753         Germany  1980-1985  70.20   Male
2754         Germany  1975-1980  68.89   Male
2755         Germany  1970-1975  67.89   Male
2756         Germany  1965-1970  67.61   Male
2757         Germany  1960-1965  67.12   Male
2758         Germany  1955-1960  66.30   Male
2759         Germany  1950-1955  65.30   Male

In [21]:
df.iloc[:30]

   Country or Area    Year(s)  Value Gender
0      Afghanistan  2095-2100  75.33   Male
1      Afghanistan  2090-2095  74.59   Male
2      Afghanistan  2085-2090  73.89   Male
3      Afghanistan  2080-2085  73.23   Male
4      Afghanistan  2075-2080  72.57   Male
5      Afghanistan  2070-2075  71.97   Male
6      Afghanistan  2065-2070  71.36   Male
7      Afghanistan  2060-2065  70.77   Male
8      Afghanistan  2055-2060  70.19   Male
9      Afghanistan  2050-2055  69.59   Male
10     Afghanistan  2045-2050  68.97   Male
11     Afghanistan  2040-2045  68.30   Male
12     Afghanistan  2035-2040  67.55   Male
13     Afghanistan  2030-2035  66.67   Male
14     Afghanistan  2025-2030  65.67   Male
15     Afghanistan  2020-2025  64.43   Male
16     Afghanistan  2015-2020  62.93   Male
17     Afghanistan  2010-2015  61.05   Male
18     Afghanistan  2005-2010  58.87   Male
19     Afghanistan  2000-2005  55.77   Male
20     Afghanistan  1995-2000  53.08   Male
21     Afghanistan  1990-1995  50.73   Male
22     Afghanistan  1985-1990  46.80   Male
23     Afghanistan  1980-1985  42.77   Male
24     Afghanistan  1975-1980  39.63   Male
25     Afghanistan  1970-1975  37.09   Male
26     Afghanistan  1965-1970  34.86   Male
27     Afghanistan  1960-1965  32.68   Male
28     Afghanistan  1955-1960  30.43   Male
29     Afghanistan  1950-1955  27.93   Male

In [30]:
df1['Gender'] = 'Female'
df1

     Country or Area    Year(s)  Value  Gender
0        Afghanistan  2095-2100  80.04  Female
1        Afghanistan  2090-2095  79.42  Female
2        Afghanistan  2085-2090  78.80  Female
3        Afghanistan  2080-2085  78.17  Female
4        Afghanistan  2075-2080  77.52  Female
5        Afghanistan  2070-2075  76.87  Female
6        Afghanistan  2065-2070  76.18  Female
7        Afghanistan  2060-2065  75.47  Female
8        Afghanistan  2055-2060  74.72  Female
9        Afghanistan  2050-2055  73.88  Female
10       Afghanistan  2045-2050  73.05  Female
11       Afghanistan  2040-2045  72.15  Female
12       Afghanistan  2035-2040  71.15  Female
13       Afghanistan  2030-2035  70.06  Female
14       Afghanistan  2025-2030  68.82  Female
15       Afghanistan  2020-2025  67.36  Female
16       Afghanistan  2015-2020  65.62  Female
17       Afghanistan  2010-2015  63.52  Female
18       Afghanistan  2005-2010  61.27  Female
19       Afghanistan  2000-2005  58.11  Female
20       Afghanistan  1995-2000  55.33  Female
21       Afghanistan  1990-1995  52.82  Female
22       Afghanistan  1985-1990  48.67  Female
23       Afghanistan  1980-1985  44.42  Female
24       Afghanistan  1975-1980  41.25  Female
25       Afghanistan  1970-1975  38.68  Female
26       Afghanistan  1965-1970  36.42  Female
27       Afghanistan  1960-1965  34.25  Female
28       Afghanistan  1955-1960  31.96  Female
29       Afghanistan  1950-1955  29.43  Female
...              ...        ...    ...     ...
8160        Zimbabwe  2095-2100  81.93  Female
8161        Zimbabwe  2090-2095  81.31  Female
8162        Zimbabwe  2085-2090  80.66  Female
8163        Zimbabwe  2080-2085  79.99  Female
8164        Zimbabwe  2075-2080  79.29  Female
8165        Zimbabwe  2070-2075  78.44  Female
8166        Zimbabwe  2065-2070  77.48  Female
8167        Zimbabwe  2060-2065  76.48  Female
8168        Zimbabwe  2055-2060  75.39  Female
8169        Zimbabwe  2050-2055  74.22  Female
8170        Zimbabwe  2045-2050  72.81  Female
8171        Zimbabwe  2040-2045  71.18  Female
8172        Zimbabwe  2035-2040  69.62  Female
8173        Zimbabwe  2030-2035  67.95  Female
8174        Zimbabwe  2025-2030  66.21  Female
8175        Zimbabwe  2020-2025  64.59  Female
8176        Zimbabwe  2015-2020  63.77  Female
8177        Zimbabwe  2010-2015  59.02  Female
8178        Zimbabwe  2005-2010  49.39  Female
8179        Zimbabwe  2000-2005  45.51  Female
8180        Zimbabwe  1995-2000  49.75  Female
8181        Zimbabwe  1990-1995  57.86  Female
8182        Zimbabwe  1985-1990  63.00  Female
8183        Zimbabwe  1980-1985  62.52  Female
8184        Zimbabwe  1975-1980  59.60  Female
8185        Zimbabwe  1970-1975  57.50  Female
8186        Zimbabwe  1965-1970  55.80  Female
8187        Zimbabwe  1960-1965  54.10  Female
8188        Zimbabwe  1955-1960  52.20  Female
8189        Zimbabwe  1950-1955  50.10  Female

[8190 rows x 4 columns]

In [31]:
df.sort_index()

     Country or Area    Year(s)  Value Gender
0        Afghanistan  2095-2100  75.33   Male
1        Afghanistan  2090-2095  74.59   Male
2        Afghanistan  2085-2090  73.89   Male
3        Afghanistan  2080-2085  73.23   Male
4        Afghanistan  2075-2080  72.57   Male
5        Afghanistan  2070-2075  71.97   Male
6        Afghanistan  2065-2070  71.36   Male
7        Afghanistan  2060-2065  70.77   Male
8        Afghanistan  2055-2060  70.19   Male
9        Afghanistan  2050-2055  69.59   Male
10       Afghanistan  2045-2050  68.97   Male
11       Afghanistan  2040-2045  68.30   Male
12       Afghanistan  2035-2040  67.55   Male
13       Afghanistan  2030-2035  66.67   Male
14       Afghanistan  2025-2030  65.67   Male
15       Afghanistan  2020-2025  64.43   Male
16       Afghanistan  2015-2020  62.93   Male
17       Afghanistan  2010-2015  61.05   Male
18       Afghanistan  2005-2010  58.87   Male
19       Afghanistan  2000-2005  55.77   Male
20       Afghanistan  1995-2000  53.08   Male
21       Afghanistan  1990-1995  50.73   Male
22       Afghanistan  1985-1990  46.80   Male
23       Afghanistan  1980-1985  42.77   Male
24       Afghanistan  1975-1980  39.63   Male
25       Afghanistan  1970-1975  37.09   Male
26       Afghanistan  1965-1970  34.86   Male
27       Afghanistan  1960-1965  32.68   Male
28       Afghanistan  1955-1960  30.43   Male
29       Afghanistan  1950-1955  27.93   Male
...              ...        ...    ...    ...
8160        Zimbabwe  2095-2100  77.51   Male
8161        Zimbabwe  2090-2095  76.87   Male
8162        Zimbabwe  2085-2090  76.22   Male
8163        Zimbabwe  2080-2085  75.55   Male
8164        Zimbabwe  2075-2080  74.86   Male
8165        Zimbabwe  2070-2075  74.11   Male
8166        Zimbabwe  2065-2070  73.21   Male
8167        Zimbabwe  2060-2065  72.23   Male
8168        Zimbabwe  2055-2060  71.19   Male
8169        Zimbabwe  2050-2055  70.10   Male
8170        Zimbabwe  2045-2050  68.82   Male
8171        Zimbabwe  2040-2045  67.43   Male
8172        Zimbabwe  2035-2040  66.03   Male
8173        Zimbabwe  2030-2035  64.45   Male
8174        Zimbabwe  2025-2030  62.69   Male
8175        Zimbabwe  2020-2025  60.93   Male
8176        Zimbabwe  2015-2020  59.91   Male
8177        Zimbabwe  2010-2015  56.10   Male
8178        Zimbabwe  2005-2010  47.20   Male
8179        Zimbabwe  2000-2005  42.70   Male
8180        Zimbabwe  1995-2000  45.06   Male
8181        Zimbabwe  1990-1995  51.67   Male
8182        Zimbabwe  1985-1990  57.48   Male
8183        Zimbabwe  1980-1985  58.59   Male
8184        Zimbabwe  1975-1980  56.10   Male
8185        Zimbabwe  1970-1975  54.09   Male
8186        Zimbabwe  1965-1970  52.50   Male
8187        Zimbabwe  1960-1965  50.90   Male
8188        Zimbabwe  1955-1960  49.00   Male
8189        Zimbabwe  1950-1955  47.00   Male

[8190 rows x 4 columns]

In [32]:
df.sort_index(ascending=False)

     Country or Area    Year(s)  Value Gender
8189        Zimbabwe  1950-1955  47.00   Male
8188        Zimbabwe  1955-1960  49.00   Male
8187        Zimbabwe  1960-1965  50.90   Male
8186        Zimbabwe  1965-1970  52.50   Male
8185        Zimbabwe  1970-1975  54.09   Male
8184        Zimbabwe  1975-1980  56.10   Male
8183        Zimbabwe  1980-1985  58.59   Male
8182        Zimbabwe  1985-1990  57.48   Male
8181        Zimbabwe  1990-1995  51.67   Male
8180        Zimbabwe  1995-2000  45.06   Male
8179        Zimbabwe  2000-2005  42.70   Male
8178        Zimbabwe  2005-2010  47.20   Male
8177        Zimbabwe  2010-2015  56.10   Male
8176        Zimbabwe  2015-2020  59.91   Male
8175        Zimbabwe  2020-2025  60.93   Male
8174        Zimbabwe  2025-2030  62.69   Male
8173        Zimbabwe  2030-2035  64.45   Male
8172        Zimbabwe  2035-2040  66.03   Male
8171        Zimbabwe  2040-2045  67.43   Male
8170        Zimbabwe  2045-2050  68.82   Male
8169        Zimbabwe  2050-2055  70.10   Male
8168        Zimbabwe  2055-2060  71.19   Male
8167        Zimbabwe  2060-2065  72.23   Male
8166        Zimbabwe  2065-2070  73.21   Male
8165        Zimbabwe  2070-2075  74.11   Male
8164        Zimbabwe  2075-2080  74.86   Male
8163        Zimbabwe  2080-2085  75.55   Male
8162        Zimbabwe  2085-2090  76.22   Male
8161        Zimbabwe  2090-2095  76.87   Male
8160        Zimbabwe  2095-2100  77.51   Male
...              ...        ...    ...    ...
29       Afghanistan  1950-1955  27.93   Male
28       Afghanistan  1955-1960  30.43   Male
27       Afghanistan  1960-1965  32.68   Male
26       Afghanistan  1965-1970  34.86   Male
25       Afghanistan  1970-1975  37.09   Male
24       Afghanistan  1975-1980  39.63   Male
23       Afghanistan  1980-1985  42.77   Male
22       Afghanistan  1985-1990  46.80   Male
21       Afghanistan  1990-1995  50.73   Male
20       Afghanistan  1995-2000  53.08   Male
19       Afghanistan  2000-2005  55.77   Male
18       Afghanistan  2005-2010  58.87   Male
17       Afghanistan  2010-2015  61.05   Male
16       Afghanistan  2015-2020  62.93   Male
15       Afghanistan  2020-2025  64.43   Male
14       Afghanistan  2025-2030  65.67   Male
13       Afghanistan  2030-2035  66.67   Male
12       Afghanistan  2035-2040  67.55   Male
11       Afghanistan  2040-2045  68.30   Male
10       Afghanistan  2045-2050  68.97   Male
9        Afghanistan  2050-2055  69.59   Male
8        Afghanistan  2055-2060  70.19   Male
7        Afghanistan  2060-2065  70.77   Male
6        Afghanistan  2065-2070  71.36   Male
5        Afghanistan  2070-2075  71.97   Male
4        Afghanistan  2075-2080  72.57   Male
3        Afghanistan  2080-2085  73.23   Male
2        Afghanistan  2085-2090  73.89   Male
1        Afghanistan  2090-2095  74.59   Male
0        Afghanistan  2095-2100  75.33   Male

[8190 rows x 4 columns]

In [33]:
df.sort_values(by='Value')

                Country or Area    Year(s)  Value Gender
1134                   Cambodia  1975-1980  11.88   Male
6021                     Rwanda  1990-1995  21.99   Male
4379                       Mali  1950-1955  26.30   Male
6689                South Sudan  1950-1955  26.63   Male
6419               Sierra Leone  1950-1955  27.09   Male
4378                       Mali  1955-1960  27.31   Male
4377                       Mali  1960-1965  27.75   Male
29                  Afghanistan  1950-1955  27.93   Male
6418               Sierra Leone  1955-1960  28.17   Male
2699                     Gambia  1950-1955  29.09   Male
6688                South Sudan  1955-1960  29.27   Male
6417               Sierra Leone  1960-1965  29.52   Male
7259                Timor-Leste  1950-1955  29.58   Male
4376                       Mali  1965-1970  29.94   Male
209                      Angola  1950-1955  30.00   Male
7254                Timor-Leste  1975-1980  30.01   Male
1049               Burkina Faso  1950-1955  30.05   Male
4949                 Mozambique  1950-1955  30.10   Male
2698                     Gambia  1955-1960  30.36   Male
28                  Afghanistan  1955-1960  30.43   Male
4049                    Liberia  1950-1955  30.75   Male
208                      Angola  1955-1960  31.10   Male
1619             Cô´te d'Ivoire  1950-1955  31.24   Male
6687                South Sudan  1960-1965  31.39   Male
6416               Sierra Leone  1965-1970  31.41   Male
2697                     Gambia  1960-1965  31.62   Male
809                      Bhutan  1950-1955  31.85   Male
4048                    Liberia  1955-1960  31.89   Male
7258                Timor-Leste  1955-1960  31.95   Male
3029                     Guinea  1950-1955  31.98   Male
...                         ...        ...    ...    ...
7920  Wallis and Futuna Islands  2095-2100    NaN   Male
7921  Wallis and Futuna Islands  2090-2095    NaN   Male
7922  Wallis and Futuna Islands  2085-2090    NaN   Male
7923  Wallis and Futuna Islands  2080-2085    NaN   Male
7924  Wallis and Futuna Islands  2075-2080    NaN   Male
7925  Wallis and Futuna Islands  2070-2075    NaN   Male
7926  Wallis and Futuna Islands  2065-2070    NaN   Male
7927  Wallis and Futuna Islands  2060-2065    NaN   Male
7928  Wallis and Futuna Islands  2055-2060    NaN   Male
7929  Wallis and Futuna Islands  2050-2055    NaN   Male
7930  Wallis and Futuna Islands  2045-2050    NaN   Male
7931  Wallis and Futuna Islands  2040-2045    NaN   Male
7932  Wallis and Futuna Islands  2035-2040    NaN   Male
7933  Wallis and Futuna Islands  2030-2035    NaN   Male
7934  Wallis and Futuna Islands  2025-2030    NaN   Male
7935  Wallis and Futuna Islands  2020-2025    NaN   Male
7936  Wallis and Futuna Islands  2015-2020    NaN   Male
7937  Wallis and Futuna Islands  2010-2015    NaN   Male
7938  Wallis and Futuna Islands  2005-2010    NaN   Male
7939  Wallis and Futuna Islands  2000-2005    NaN   Male
7940  Wallis and Futuna Islands  1995-2000    NaN   Male
7941  Wallis and Futuna Islands  1990-1995    NaN   Male
7942  Wallis and Futuna Islands  1985-1990    NaN   Male
7943  Wallis and Futuna Islands  1980-1985    NaN   Male
7944  Wallis and Futuna Islands  1975-1980    NaN   Male
7945  Wallis and Futuna Islands  1970-1975    NaN   Male
7946  Wallis and Futuna Islands  1965-1970    NaN   Male
7947  Wallis and Futuna Islands  1960-1965    NaN   Male
7948  Wallis and Futuna Islands  1955-1960    NaN   Male
7949  Wallis and Futuna Islands  1950-1955    NaN   Male

[8190 rows x 4 columns]

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8190 entries, 0 to 8189
Data columns (total 4 columns):
Country or Area    8190 non-null object
Year(s)            8190 non-null object
Value              7230 non-null float64
Gender             8190 non-null object
dtypes: float64(1), object(3)
memory usage: 256.0+ KB