In [5]:
import pandas as pd

PATH = "movie_recommendations.xlsx"

df = pd.read_excel(PATH)

FileNotFoundError: [Errno 2] No such file or directory: 'movie_recommendations.xlsx'

In [2]:
print("""
    Kristians and Felipes Movie Recommender:

    Enter your favourite genre or reviwer
    and the program will recommend a movie.

""")

    Kristians and Felipes Movie Recommender:

    Enter your favourite genre or reviwer
    and the program will recommend a movie.

In [3]:
print("Enter a rating number 1 - 5 (or leave it empty): ", end="")
rating = float(input())

if rating:
    r = df[df['Rating'] == rating]
else:
    r = df
    
print("Enter a reviewer (or leave it empty): ", end="")
reviewer = input()

if reviewer:
    re = r[r['Reviewer'] == reviewer]
else:
    re = r

print("Enter a genre (or leave it empty): ", end="")
genre = input()

if genre:
    g = re[re['Genre'] == genre]
else:
    g = re


if g.shape[0] > 0:
    result = g.sort_values('Rating', ascending=False)
    print(result.head(3).sample(1))
else:
    print("Sorry, no results!")

Enter a rating number 1 - 5 (or leave it empty): 3
Enter a reviewer (or leave it empty):
Enter a genre (or leave it empty):
                      Name   Genre  Rating Reviewer
5  Texas Chainsaw Massacre  Horror     3.0     Paul

In [4]:
'''
create a DB connection = import sqlite3

iterate through the entries

wirte
'''

'\ncreate a DB connection = import sqlite3\n\niterate through the entries\n\nwirte\n'

# 2 part DB connection

In [5]:
import sqlite3

In [6]:
DB_SETUP = '''
CREATE TABLE IF NOT EXISTS 'reviews' (
title VARCHAR(250),
genre VARCHAR(64),
rating INTEGER,
reviewer VARCHAR(64)
);
'''

In [7]:
db = sqlite3.connect('movies.db')
db.executescript(DB_SETUP)

In [8]:
for i, row in df.iterrows():
    print(row['Genre'], row['Rating'])
    query = 'INSERT INTO reviews VALUES (?,?,?,?)'
    db.execute(query,(row['Name'], row['Genre'], row['Rating'], row['Reviewer']))
    
    db.commit()
db.close()

Thriller 5.0
drama 4.0
Thriller 5.0
Cartoon 5.0
Horror 4.0
Horror 3.0
Comedy 5.0
drama 4.0
cartoon 5.0
Crime 5.0
nan 5.0
?? 4.0
Crime/Drama? nan
Crime 5.0
Dark Comedy 5.0
Fantasy 4.0
Science Fiction 1.0
Kaiju 1.0
Kaiju 1.0
Science Fiction 5.0
Mystery 5.0
Drama 5.0
Crime 2.0
Horror 3.0
Comedy 5.0
Drama 5.0
Drama 2.0
comedy 4.0
Sci-Fi 5.0
Comedy 4.0
Comedy 1.0
Drama 5.0
Thriller 5.0
Revolutionary 5.0
Biopic 4.0
nan 2.0
Comedy 1.0
Farce 1.0
Comedy 3.0
Adventure 1.0
Musical 1.0
Musical 2.0
Drama 3.0
Drama 5.0
nan 1.0
Revolutionary 3.0
Drama 4.0
Data Science 5.0
Sci-Fi 4.0
nan nan
Sci-Fi 5.0
nan nan
Data Science 3.0
Drama 1.0
Science fiction nan
Drama 4.0
Sci-Fi 4.0

In [9]:
db = sqlite3.connect('movies.db')

In [10]:
query = 'SELECT * FROM reviews'

result = db.execute(query)

result

In [11]:
for row in result:
    print(row)

('Inception', 'Thriller', 5, 'Paul')
('Titanic', 'drama', 4, 'Kristian')
('Memento', 'Thriller', 5, 'Helena')
('The Lion King', 'Cartoon', 5, 'Paul')
('Evil Dead', 'Horror', 4, 'Tom')
('Texas Chainsaw Massacre', 'Horror', 3, 'Paul')
('Carnage', 'Comedy', 5, 'Matthias')
('Titanic', 'drama', 4, 'Kristian')
('Shrek', 'cartoon', 5, 'Kristian')
('Pulp Fiction', 'Crime', 5, 'Helena')
('Pulp Fiction', None, 5, 'Kristian')
('Rocky Horror Picture', '??', 4, 'Julian')
('Run Lola Run', 'Crime/Drama?', None, 'Paul')
('The Godfather', 'Crime', 5, 'Felipe')
('In Bruges', 'Dark Comedy', 5, 'Paul')
('Metropolis', 'Fantasy', 4, 'Tom')
('Avatar', 'Science Fiction', 1, 'Matthias')
('Pacific Rim 2', 'Kaiju', 1, 'Kristian')
('Monster X vs the G7 Summit', 'Kaiju', 1, 'Kristian')
('The Empire Strikes Back', 'Science Fiction', 5, 'Matthias')
('Der unsichtbare Gast', 'Mystery', 5, 'Helena')
('The Silence of the Lambs', 'Drama', 5, 'Felipe')
('Mighty Morphin Power Rangers', 'Crime', 2, 'Paul')
('The Ring', 'Horror', 3, 'Paul')
('Big Lebowski', 'Comedy', 5, 'Tom')
('Lion', 'Drama', 5, 'Paul')
('Sleepy Hollow', 'Drama', 2, 'Felipe')
('Monty Python and the Holy Grail', 'comedy', 4, 'Kristian')
('Cloud Atlas', 'Sci-Fi', 5, 'Manohar')
('Budapest Hotel', 'Comedy', 4, 'Julian')
('Teenage Mutant Ninja Turtles', 'Comedy', 1, 'Helena')
('Casablanca', 'Drama', 5, 'Glynis')
('Rear Window', 'Thriller', 5, 'Glynis')
('Fight Club', 'Revolutionary', 5, 'Manohar')
('A beautiful mind', 'Biopic', 4, 'Matthias')
('Kill Bill 1', None, 2, 'Julian')
('Observe and report', 'Comedy', 1, 'Manohar')
('Titanic', 'Farce', 1, 'Tom')
('Grease', 'Comedy', 3, 'Nicolas')
('Lawrence of Arabia', 'Adventure', 1, 'Felipe')
('Mamma Mia', 'Musical', 1, 'Manohar')
('Mamma Mia', 'Musical', 2, 'Tom')
('Gone with the Wind', 'Drama', 3, 'Felipe')
('The Imitation Game', 'Drama', 5, 'Paul')
('Ready Player 1', None, 1, 'Julian')
('Brazil', 'Revolutionary', 3, 'Kristian')
('Good Will Hunting', 'Drama', 4, 'Matthias')
('Citizen 4', 'Data Science', 5, 'Kristian')
('Ex Machina', 'Sci-Fi', 4, 'Manohar')
(None, None, None, None)
('2001: A space odyssey', 'Sci-Fi', 5, 'Matthias')
(None, None, None, None)
('Moneyball', 'Data Science', 3, 'Kristian')
('12 Angry Men', 'Drama', 1, 'Felipe')
('Star Wars', 'Science fiction', None, 'Nicolas')
('Adaptation', 'Drama', 4, 'Manohar')
('12 Monkeys', 'Sci-Fi', 4, 'Helena')
('Inception', 'Thriller', 5, 'Paul')
('Titanic', 'drama', 4, 'Kristian')
('Memento', 'Thriller', 5, 'Helena')
('The Lion King', 'Cartoon', 5, 'Paul')
('Evil Dead', 'Horror', 4, 'Tom')
('Texas Chainsaw Massacre', 'Horror', 3, 'Paul')
('Carnage', 'Comedy', 5, 'Matthias')
('Titanic', 'drama', 4, 'Kristian')
('Shrek', 'cartoon', 5, 'Kristian')
('Pulp Fiction', 'Crime', 5, 'Helena')
('Pulp Fiction', None, 5, 'Kristian')
('Rocky Horror Picture', '??', 4, 'Julian')
('Run Lola Run', 'Crime/Drama?', None, 'Paul')
('The Godfather', 'Crime', 5, 'Felipe')
('In Bruges', 'Dark Comedy', 5, 'Paul')
('Metropolis', 'Fantasy', 4, 'Tom')
('Avatar', 'Science Fiction', 1, 'Matthias')
('Pacific Rim 2', 'Kaiju', 1, 'Kristian')
('Monster X vs the G7 Summit', 'Kaiju', 1, 'Kristian')
('The Empire Strikes Back', 'Science Fiction', 5, 'Matthias')
('Der unsichtbare Gast', 'Mystery', 5, 'Helena')
('The Silence of the Lambs', 'Drama', 5, 'Felipe')
('Mighty Morphin Power Rangers', 'Crime', 2, 'Paul')
('The Ring', 'Horror', 3, 'Paul')
('Big Lebowski', 'Comedy', 5, 'Tom')
('Lion', 'Drama', 5, 'Paul')
('Sleepy Hollow', 'Drama', 2, 'Felipe')
('Monty Python and the Holy Grail', 'comedy', 4, 'Kristian')
('Cloud Atlas', 'Sci-Fi', 5, 'Manohar')
('Budapest Hotel', 'Comedy', 4, 'Julian')
('Teenage Mutant Ninja Turtles', 'Comedy', 1, 'Helena')
('Casablanca', 'Drama', 5, 'Glynis')
('Rear Window', 'Thriller', 5, 'Glynis')
('Fight Club', 'Revolutionary', 5, 'Manohar')
('A beautiful mind', 'Biopic', 4, 'Matthias')
('Kill Bill 1', None, 2, 'Julian')
('Observe and report', 'Comedy', 1, 'Manohar')
('Titanic', 'Farce', 1, 'Tom')
('Grease', 'Comedy', 3, 'Nicolas')
('Lawrence of Arabia', 'Adventure', 1, 'Felipe')
('Mamma Mia', 'Musical', 1, 'Manohar')
('Mamma Mia', 'Musical', 2, 'Tom')
('Gone with the Wind', 'Drama', 3, 'Felipe')
('The Imitation Game', 'Drama', 5, 'Paul')
('Ready Player 1', None, 1, 'Julian')
('Brazil', 'Revolutionary', 3, 'Kristian')
('Good Will Hunting', 'Drama', 4, 'Matthias')
('Citizen 4', 'Data Science', 5, 'Kristian')
('Ex Machina', 'Sci-Fi', 4, 'Manohar')
(None, None, None, None)
('2001: A space odyssey', 'Sci-Fi', 5, 'Matthias')
(None, None, None, None)
('Moneyball', 'Data Science', 3, 'Kristian')
('12 Angry Men', 'Drama', 1, 'Felipe')
('Star Wars', 'Science fiction', None, 'Nicolas')
('Adaptation', 'Drama', 4, 'Manohar')
('12 Monkeys', 'Sci-Fi', 4, 'Helena')
('Inception', 'Thriller', 5, 'Paul')
('Titanic', 'drama', 4, 'Kristian')
('Memento', 'Thriller', 5, 'Helena')
('The Lion King', 'Cartoon', 5, 'Paul')
('Evil Dead', 'Horror', 4, 'Tom')
('Texas Chainsaw Massacre', 'Horror', 3, 'Paul')
('Carnage', 'Comedy', 5, 'Matthias')
('Titanic', 'drama', 4, 'Kristian')
('Shrek', 'cartoon', 5, 'Kristian')
('Pulp Fiction', 'Crime', 5, 'Helena')
('Pulp Fiction', None, 5, 'Kristian')
('Rocky Horror Picture', '??', 4, 'Julian')
('Run Lola Run', 'Crime/Drama?', None, 'Paul')
('The Godfather', 'Crime', 5, 'Felipe')
('In Bruges', 'Dark Comedy', 5, 'Paul')
('Metropolis', 'Fantasy', 4, 'Tom')
('Avatar', 'Science Fiction', 1, 'Matthias')
('Pacific Rim 2', 'Kaiju', 1, 'Kristian')
('Monster X vs the G7 Summit', 'Kaiju', 1, 'Kristian')
('The Empire Strikes Back', 'Science Fiction', 5, 'Matthias')
('Der unsichtbare Gast', 'Mystery', 5, 'Helena')
('The Silence of the Lambs', 'Drama', 5, 'Felipe')
('Mighty Morphin Power Rangers', 'Crime', 2, 'Paul')
('The Ring', 'Horror', 3, 'Paul')
('Big Lebowski', 'Comedy', 5, 'Tom')
('Lion', 'Drama', 5, 'Paul')
('Sleepy Hollow', 'Drama', 2, 'Felipe')
('Monty Python and the Holy Grail', 'comedy', 4, 'Kristian')
('Cloud Atlas', 'Sci-Fi', 5, 'Manohar')
('Budapest Hotel', 'Comedy', 4, 'Julian')
('Teenage Mutant Ninja Turtles', 'Comedy', 1, 'Helena')
('Casablanca', 'Drama', 5, 'Glynis')
('Rear Window', 'Thriller', 5, 'Glynis')
('Fight Club', 'Revolutionary', 5, 'Manohar')
('A beautiful mind', 'Biopic', 4, 'Matthias')
('Kill Bill 1', None, 2, 'Julian')
('Observe and report', 'Comedy', 1, 'Manohar')
('Titanic', 'Farce', 1, 'Tom')
('Grease', 'Comedy', 3, 'Nicolas')
('Lawrence of Arabia', 'Adventure', 1, 'Felipe')
('Mamma Mia', 'Musical', 1, 'Manohar')
('Mamma Mia', 'Musical', 2, 'Tom')
('Gone with the Wind', 'Drama', 3, 'Felipe')
('The Imitation Game', 'Drama', 5, 'Paul')
('Ready Player 1', None, 1, 'Julian')
('Brazil', 'Revolutionary', 3, 'Kristian')
('Good Will Hunting', 'Drama', 4, 'Matthias')
('Citizen 4', 'Data Science', 5, 'Kristian')
('Ex Machina', 'Sci-Fi', 4, 'Manohar')
(None, None, None, None)
('2001: A space odyssey', 'Sci-Fi', 5, 'Matthias')
(None, None, None, None)
('Moneyball', 'Data Science', 3, 'Kristian')
('12 Angry Men', 'Drama', 1, 'Felipe')
('Star Wars', 'Science fiction', None, 'Nicolas')
('Adaptation', 'Drama', 4, 'Manohar')
('12 Monkeys', 'Sci-Fi', 4, 'Helena')
('Inception', 'Thriller', 5, 'Paul')
('Titanic', 'drama', 4, 'Kristian')
('Memento', 'Thriller', 5, 'Helena')
('The Lion King', 'Cartoon', 5, 'Paul')
('Evil Dead', 'Horror', 4, 'Tom')
('Texas Chainsaw Massacre', 'Horror', 3, 'Paul')
('Carnage', 'Comedy', 5, 'Matthias')
('Titanic', 'drama', 4, 'Kristian')
('Shrek', 'cartoon', 5, 'Kristian')
('Pulp Fiction', 'Crime', 5, 'Helena')
('Pulp Fiction', None, 5, 'Kristian')
('Rocky Horror Picture', '??', 4, 'Julian')
('Run Lola Run', 'Crime/Drama?', None, 'Paul')
('The Godfather', 'Crime', 5, 'Felipe')
('In Bruges', 'Dark Comedy', 5, 'Paul')
('Metropolis', 'Fantasy', 4, 'Tom')
('Avatar', 'Science Fiction', 1, 'Matthias')
('Pacific Rim 2', 'Kaiju', 1, 'Kristian')
('Monster X vs the G7 Summit', 'Kaiju', 1, 'Kristian')
('The Empire Strikes Back', 'Science Fiction', 5, 'Matthias')
('Der unsichtbare Gast', 'Mystery', 5, 'Helena')
('The Silence of the Lambs', 'Drama', 5, 'Felipe')
('Mighty Morphin Power Rangers', 'Crime', 2, 'Paul')
('The Ring', 'Horror', 3, 'Paul')
('Big Lebowski', 'Comedy', 5, 'Tom')
('Lion', 'Drama', 5, 'Paul')
('Sleepy Hollow', 'Drama', 2, 'Felipe')
('Monty Python and the Holy Grail', 'comedy', 4, 'Kristian')
('Cloud Atlas', 'Sci-Fi', 5, 'Manohar')
('Budapest Hotel', 'Comedy', 4, 'Julian')
('Teenage Mutant Ninja Turtles', 'Comedy', 1, 'Helena')
('Casablanca', 'Drama', 5, 'Glynis')
('Rear Window', 'Thriller', 5, 'Glynis')
('Fight Club', 'Revolutionary', 5, 'Manohar')
('A beautiful mind', 'Biopic', 4, 'Matthias')
('Kill Bill 1', None, 2, 'Julian')
('Observe and report', 'Comedy', 1, 'Manohar')
('Titanic', 'Farce', 1, 'Tom')
('Grease', 'Comedy', 3, 'Nicolas')
('Lawrence of Arabia', 'Adventure', 1, 'Felipe')
('Mamma Mia', 'Musical', 1, 'Manohar')
('Mamma Mia', 'Musical', 2, 'Tom')
('Gone with the Wind', 'Drama', 3, 'Felipe')
('The Imitation Game', 'Drama', 5, 'Paul')
('Ready Player 1', None, 1, 'Julian')
('Brazil', 'Revolutionary', 3, 'Kristian')
('Good Will Hunting', 'Drama', 4, 'Matthias')
('Citizen 4', 'Data Science', 5, 'Kristian')
('Ex Machina', 'Sci-Fi', 4, 'Manohar')
(None, None, None, None)
('2001: A space odyssey', 'Sci-Fi', 5, 'Matthias')
(None, None, None, None)
('Moneyball', 'Data Science', 3, 'Kristian')
('12 Angry Men', 'Drama', 1, 'Felipe')
('Star Wars', 'Science fiction', None, 'Nicolas')
('Adaptation', 'Drama', 4, 'Manohar')
('12 Monkeys', 'Sci-Fi', 4, 'Helena')
('Inception', 'Thriller', 5, 'Paul')
('Titanic', 'drama', 4, 'Kristian')
('Memento', 'Thriller', 5, 'Helena')
('The Lion King', 'Cartoon', 5, 'Paul')
('Evil Dead', 'Horror', 4, 'Tom')
('Texas Chainsaw Massacre', 'Horror', 3, 'Paul')
('Carnage', 'Comedy', 5, 'Matthias')
('Titanic', 'drama', 4, 'Kristian')
('Shrek', 'cartoon', 5, 'Kristian')
('Pulp Fiction', 'Crime', 5, 'Helena')
('Pulp Fiction', None, 5, 'Kristian')
('Rocky Horror Picture', '??', 4, 'Julian')
('Run Lola Run', 'Crime/Drama?', None, 'Paul')
('The Godfather', 'Crime', 5, 'Felipe')
('In Bruges', 'Dark Comedy', 5, 'Paul')
('Metropolis', 'Fantasy', 4, 'Tom')
('Avatar', 'Science Fiction', 1, 'Matthias')
('Pacific Rim 2', 'Kaiju', 1, 'Kristian')
('Monster X vs the G7 Summit', 'Kaiju', 1, 'Kristian')
('The Empire Strikes Back', 'Science Fiction', 5, 'Matthias')
('Der unsichtbare Gast', 'Mystery', 5, 'Helena')
('The Silence of the Lambs', 'Drama', 5, 'Felipe')
('Mighty Morphin Power Rangers', 'Crime', 2, 'Paul')
('The Ring', 'Horror', 3, 'Paul')
('Big Lebowski', 'Comedy', 5, 'Tom')
('Lion', 'Drama', 5, 'Paul')
('Sleepy Hollow', 'Drama', 2, 'Felipe')
('Monty Python and the Holy Grail', 'comedy', 4, 'Kristian')
('Cloud Atlas', 'Sci-Fi', 5, 'Manohar')
('Budapest Hotel', 'Comedy', 4, 'Julian')
('Teenage Mutant Ninja Turtles', 'Comedy', 1, 'Helena')
('Casablanca', 'Drama', 5, 'Glynis')
('Rear Window', 'Thriller', 5, 'Glynis')
('Fight Club', 'Revolutionary', 5, 'Manohar')
('A beautiful mind', 'Biopic', 4, 'Matthias')
('Kill Bill 1', None, 2, 'Julian')
('Observe and report', 'Comedy', 1, 'Manohar')
('Titanic', 'Farce', 1, 'Tom')
('Grease', 'Comedy', 3, 'Nicolas')
('Lawrence of Arabia', 'Adventure', 1, 'Felipe')
('Mamma Mia', 'Musical', 1, 'Manohar')
('Mamma Mia', 'Musical', 2, 'Tom')
('Gone with the Wind', 'Drama', 3, 'Felipe')
('The Imitation Game', 'Drama', 5, 'Paul')
('Ready Player 1', None, 1, 'Julian')
('Brazil', 'Revolutionary', 3, 'Kristian')
('Good Will Hunting', 'Drama', 4, 'Matthias')
('Citizen 4', 'Data Science', 5, 'Kristian')
('Ex Machina', 'Sci-Fi', 4, 'Manohar')
(None, None, None, None)
('2001: A space odyssey', 'Sci-Fi', 5, 'Matthias')
(None, None, None, None)
('Moneyball', 'Data Science', 3, 'Kristian')
('12 Angry Men', 'Drama', 1, 'Felipe')
('Star Wars', 'Science fiction', None, 'Nicolas')
('Adaptation', 'Drama', 4, 'Manohar')
('12 Monkeys', 'Sci-Fi', 4, 'Helena')
('Inception', 'Thriller', 5, 'Paul')
('Titanic', 'drama', 4, 'Kristian')
('Memento', 'Thriller', 5, 'Helena')
('The Lion King', 'Cartoon', 5, 'Paul')
('Evil Dead', 'Horror', 4, 'Tom')
('Texas Chainsaw Massacre', 'Horror', 3, 'Paul')
('Carnage', 'Comedy', 5, 'Matthias')
('Titanic', 'drama', 4, 'Kristian')
('Shrek', 'cartoon', 5, 'Kristian')
('Pulp Fiction', 'Crime', 5, 'Helena')
('Pulp Fiction', None, 5, 'Kristian')
('Rocky Horror Picture', '??', 4, 'Julian')
('Run Lola Run', 'Crime/Drama?', None, 'Paul')
('The Godfather', 'Crime', 5, 'Felipe')
('In Bruges', 'Dark Comedy', 5, 'Paul')
('Metropolis', 'Fantasy', 4, 'Tom')
('Avatar', 'Science Fiction', 1, 'Matthias')
('Pacific Rim 2', 'Kaiju', 1, 'Kristian')
('Monster X vs the G7 Summit', 'Kaiju', 1, 'Kristian')
('The Empire Strikes Back', 'Science Fiction', 5, 'Matthias')
('Der unsichtbare Gast', 'Mystery', 5, 'Helena')
('The Silence of the Lambs', 'Drama', 5, 'Felipe')
('Mighty Morphin Power Rangers', 'Crime', 2, 'Paul')
('The Ring', 'Horror', 3, 'Paul')
('Big Lebowski', 'Comedy', 5, 'Tom')
('Lion', 'Drama', 5, 'Paul')
('Sleepy Hollow', 'Drama', 2, 'Felipe')
('Monty Python and the Holy Grail', 'comedy', 4, 'Kristian')
('Cloud Atlas', 'Sci-Fi', 5, 'Manohar')
('Budapest Hotel', 'Comedy', 4, 'Julian')
('Teenage Mutant Ninja Turtles', 'Comedy', 1, 'Helena')
('Casablanca', 'Drama', 5, 'Glynis')
('Rear Window', 'Thriller', 5, 'Glynis')
('Fight Club', 'Revolutionary', 5, 'Manohar')
('A beautiful mind', 'Biopic', 4, 'Matthias')
('Kill Bill 1', None, 2, 'Julian')
('Observe and report', 'Comedy', 1, 'Manohar')
('Titanic', 'Farce', 1, 'Tom')
('Grease', 'Comedy', 3, 'Nicolas')
('Lawrence of Arabia', 'Adventure', 1, 'Felipe')
('Mamma Mia', 'Musical', 1, 'Manohar')
('Mamma Mia', 'Musical', 2, 'Tom')
('Gone with the Wind', 'Drama', 3, 'Felipe')
('The Imitation Game', 'Drama', 5, 'Paul')
('Ready Player 1', None, 1, 'Julian')
('Brazil', 'Revolutionary', 3, 'Kristian')
('Good Will Hunting', 'Drama', 4, 'Matthias')
('Citizen 4', 'Data Science', 5, 'Kristian')
('Ex Machina', 'Sci-Fi', 4, 'Manohar')
(None, None, None, None)
('2001: A space odyssey', 'Sci-Fi', 5, 'Matthias')
(None, None, None, None)
('Moneyball', 'Data Science', 3, 'Kristian')
('12 Angry Men', 'Drama', 1, 'Felipe')
('Star Wars', 'Science fiction', None, 'Nicolas')
('Adaptation', 'Drama', 4, 'Manohar')
('12 Monkeys', 'Sci-Fi', 4, 'Helena')

In [12]:

query = 'SELECT * FROM reviews WHERE Rating=4'

result = db.execute(query)

result

In [13]:
for row in result:
    print(row)

('Titanic', 'drama', 4, 'Kristian')
('Evil Dead', 'Horror', 4, 'Tom')
('Titanic', 'drama', 4, 'Kristian')
('Rocky Horror Picture', '??', 4, 'Julian')
('Metropolis', 'Fantasy', 4, 'Tom')
('Monty Python and the Holy Grail', 'comedy', 4, 'Kristian')
('Budapest Hotel', 'Comedy', 4, 'Julian')
('A beautiful mind', 'Biopic', 4, 'Matthias')
('Good Will Hunting', 'Drama', 4, 'Matthias')
('Ex Machina', 'Sci-Fi', 4, 'Manohar')
('Adaptation', 'Drama', 4, 'Manohar')
('12 Monkeys', 'Sci-Fi', 4, 'Helena')
('Titanic', 'drama', 4, 'Kristian')
('Evil Dead', 'Horror', 4, 'Tom')
('Titanic', 'drama', 4, 'Kristian')
('Rocky Horror Picture', '??', 4, 'Julian')
('Metropolis', 'Fantasy', 4, 'Tom')
('Monty Python and the Holy Grail', 'comedy', 4, 'Kristian')
('Budapest Hotel', 'Comedy', 4, 'Julian')
('A beautiful mind', 'Biopic', 4, 'Matthias')
('Good Will Hunting', 'Drama', 4, 'Matthias')
('Ex Machina', 'Sci-Fi', 4, 'Manohar')
('Adaptation', 'Drama', 4, 'Manohar')
('12 Monkeys', 'Sci-Fi', 4, 'Helena')
('Titanic', 'drama', 4, 'Kristian')
('Evil Dead', 'Horror', 4, 'Tom')
('Titanic', 'drama', 4, 'Kristian')
('Rocky Horror Picture', '??', 4, 'Julian')
('Metropolis', 'Fantasy', 4, 'Tom')
('Monty Python and the Holy Grail', 'comedy', 4, 'Kristian')
('Budapest Hotel', 'Comedy', 4, 'Julian')
('A beautiful mind', 'Biopic', 4, 'Matthias')
('Good Will Hunting', 'Drama', 4, 'Matthias')
('Ex Machina', 'Sci-Fi', 4, 'Manohar')
('Adaptation', 'Drama', 4, 'Manohar')
('12 Monkeys', 'Sci-Fi', 4, 'Helena')
('Titanic', 'drama', 4, 'Kristian')
('Evil Dead', 'Horror', 4, 'Tom')
('Titanic', 'drama', 4, 'Kristian')
('Rocky Horror Picture', '??', 4, 'Julian')
('Metropolis', 'Fantasy', 4, 'Tom')
('Monty Python and the Holy Grail', 'comedy', 4, 'Kristian')
('Budapest Hotel', 'Comedy', 4, 'Julian')
('A beautiful mind', 'Biopic', 4, 'Matthias')
('Good Will Hunting', 'Drama', 4, 'Matthias')
('Ex Machina', 'Sci-Fi', 4, 'Manohar')
('Adaptation', 'Drama', 4, 'Manohar')
('12 Monkeys', 'Sci-Fi', 4, 'Helena')
('Titanic', 'drama', 4, 'Kristian')
('Evil Dead', 'Horror', 4, 'Tom')
('Titanic', 'drama', 4, 'Kristian')
('Rocky Horror Picture', '??', 4, 'Julian')
('Metropolis', 'Fantasy', 4, 'Tom')
('Monty Python and the Holy Grail', 'comedy', 4, 'Kristian')
('Budapest Hotel', 'Comedy', 4, 'Julian')
('A beautiful mind', 'Biopic', 4, 'Matthias')
('Good Will Hunting', 'Drama', 4, 'Matthias')
('Ex Machina', 'Sci-Fi', 4, 'Manohar')
('Adaptation', 'Drama', 4, 'Manohar')
('12 Monkeys', 'Sci-Fi', 4, 'Helena')
('Titanic', 'drama', 4, 'Kristian')
('Evil Dead', 'Horror', 4, 'Tom')
('Titanic', 'drama', 4, 'Kristian')
('Rocky Horror Picture', '??', 4, 'Julian')
('Metropolis', 'Fantasy', 4, 'Tom')
('Monty Python and the Holy Grail', 'comedy', 4, 'Kristian')
('Budapest Hotel', 'Comedy', 4, 'Julian')
('A beautiful mind', 'Biopic', 4, 'Matthias')
('Good Will Hunting', 'Drama', 4, 'Matthias')
('Ex Machina', 'Sci-Fi', 4, 'Manohar')
('Adaptation', 'Drama', 4, 'Manohar')
('12 Monkeys', 'Sci-Fi', 4, 'Helena')

In [16]:
db.close()